version: '3.8'

services:
  postgres:
    image: postgres:17.4-alpine
    container_name: movie-db
    restart: always
    environment:
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_password
      POSTGRES_DB: movie_database
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  movie-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-api
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: movie_user
      DB_PASSWORD: movie_password
      DB_NAME: movie_database
    ports:
      - "8888:8080"
    volumes:
      - ./internal/db/migrations:/app/internal/db/migrations

volumes:
  postgres_data:
