version: '3.8'

services:
  postgres:
    image: postgres:17.4-alpine
    container_name: movie-db
    restart: always
    environment:
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_password
      POSTGRES_DB: movie_database
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
